[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nmexec"
version = "0.0.1"
description = "Network Model Executor Allows to process data over the network"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["psutil", "opencv-python"]

[project.scripts]
nmexec = "nmexec.__main__:main"

[tool.setuptools.packages.find]
where = ["src"]
include = ["*"]

[tool.setuptools.package-data]
"*" = ["*"]
